# Generated by Django 5.0.7 on 2024-07-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='ar_content',
            field=models.FileField(blank=True, null=True, upload_to='content_ar', verbose_name='AR document'),
        ),
        migrations.AlterField(
            model_name='content',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Скидка действительна до'),
        ),
    ]
