# Generated by Django 5.0.7 on 2024-07-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_content_ar_content_alter_content_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='ar_content',
        ),
        migrations.AddField(
            model_name='content',
            name='ar_content_bin',
            field=models.FileField(blank=True, null=True, upload_to='content_ar', verbose_name='AR document (.bin)'),
        ),
        migrations.AddField(
            model_name='content',
            name='ar_content_gltf',
            field=models.FileField(blank=True, null=True, upload_to='content_ar', verbose_name='AR document (.gltf)'),
        ),
        migrations.AddField(
            model_name='content',
            name='ar_content_texture',
            field=models.FileField(blank=True, null=True, upload_to='content_ar', verbose_name='AR document (.jpg)'),
        ),
    ]
